<?php

	//application details
		$apps[$x]['name'] = "Operator Panel";
		$apps[$x]['uuid'] = "dd3d173a-5d51-4231-ab22-b18c5b712bb2";
		$apps[$x]['category'] = "Switch";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Operator panel shows the status.";
		$apps[$x]['description']['en-gb'] = "Operator panel shows the status.";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "Das Bedienfeld zeigt den Status an.";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "Das Bedienfeld zeigt den Status an.";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['ka-ge'] = "ოპერატორის პანელი სტატუსს აჩვენებს.";
		$apps[$x]['description']['nl-nl'] = "Bedieningspaneel laat de status zien";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "Canais ativos no sistema.";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_manage";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_eavesdrop";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_hangup";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_record";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_call_details";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_on_demand";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_emergency";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_emergency_broadcast";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "operator_panel_alarm_test";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";

	//default settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "569280f2-a433-4eaf-9c08-945efdc6cf8f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "refresh";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1500";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set the refresh rate in seconds (<=120) or milliseconds (>=500).";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "0c273cad-1ee4-48d9-9336-08bc8260579a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "group_extensions";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set if extensions are grouped by call_group when viewing all extensions.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "0d3b16b0-5cd6-4d0e-8b58-967972362ef8";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "show_unregistered";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set whether unregistered extensions are displayed or not.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a9ccd174-5ae1-4f90-8ee2-b79a183a04f8";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "theme";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "operator_panel_main_background_color";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "#ffffff";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set main background color (and opacity) of extensions";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b9d34460-db41-40d5-becd-5da037fa8942";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "theme";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "operator_panel_sub_background_color";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "#e5eaf5";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set sub background color (and opacity) of extensions";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9cb6477d-0454-4b9c-b0fb-11c258d4f35f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "theme";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "operator_panel_border_color";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "#b9c5d8";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set border color (and opacity) of extensions";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6d85f8c1-ef41-4d8c-a70f-6a9d98974bb7";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_host";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "192.168.50.1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Emergency alarm TCP client host. Default is 192.168.50.1 and can be overridden by default or domain settings.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f95e95f2-f51a-4b2e-a0eb-ac28d29ddb4f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_port";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "9003";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Emergency alarm TCP client port. Default is 9003 and can be overridden by default or domain settings.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f84ced02-a94d-442e-a450-9aee8503a8bb";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_presence_ttl";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "90";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Seconds before operator presence expires.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f124ff11-f3da-4ba6-a67b-aaf039f7eeff";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_job_timeout";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Seconds the web API waits for the alarm service job result.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1a9c1e6b-b9c6-4468-ad6b-f79f3a8a5803";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_socket_timeout_ms";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1200";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Emergency alarm TCP socket timeout in milliseconds.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "37539581-07cd-4add-8d78-d64ab3115892";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_audio_folder";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Alarm device audio folder number for loop playback.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9bc408d4-8644-4d7f-80a4-03f1092a83a4";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_audio_track";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Alarm device track number for loop playback.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c1278375-e82c-4fc4-b5fc-1e8a24a20caa";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_strobe_mode";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Alarm device strobe mode value for emergency alarm activation.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d9553b3c-f159-4b1a-a8d1-f31bcb2d9b2c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "operator_panel";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "emergency_alarm_audio_volume";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "30";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Alarm device playback volume for emergency alarm activation.";
		$y++;

	//schema details
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_emergency_calls";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_call_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Domain UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "call_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Call UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "direction";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Call direction: user_to_dispatcher or dispatcher_to_user";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "caller_extension";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Caller extension";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "callee_extension";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Callee extension";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency type: single, group, or broadcast";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "target_group";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Target group for group emergency calls";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "recording_path";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Path to call recording file";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "start_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call start time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "answer_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call answer time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "end_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call end time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "auto_answer_triggered";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Whether auto-answer was triggered";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "status";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call status";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert user";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_state";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm state";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_trigger_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm trigger time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_ack_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm acknowledge time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_clear_time";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm clear time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_clear_reason";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm clear reason";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_error";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm error";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "alarm_last_response";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm last response";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update user";
		$y++;

		$apps[$x]['db'][$y]['table']['name'] = "v_emergency_alarm_logs";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_alarm_log_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency alarm log UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Domain UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_call_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "action";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Alarm action";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "request_payload";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Request payload";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "response_payload";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Response payload";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "status";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Action status";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "error_message";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Error message";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert user";
		$y++;

		$apps[$x]['db'][$y]['table']['name'] = "v_operator_panel_presence";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "operator_panel_presence_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Operator panel presence UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Domain UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "tab_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Browser tab UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "extension";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Registered extension";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_uri";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "SIP URI";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "client_ip";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Client IP";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_agent";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User agent";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_seen";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last seen";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "expires_at";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Expires at";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert user";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update user";
		$y++;

		$apps[$x]['db'][$y]['table']['name'] = "v_emergency_alarm_jobs";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_alarm_job_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency alarm job UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Domain UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_call_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency call UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "action";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Job action";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "payload";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Job payload";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "status";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Job status";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "result_payload";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Result payload";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "error_message";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Error message";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Insert user";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update user";
		$y++;

		$apps[$x]['db'][$y]['table']['name'] = "v_emergency_alarm_runtime";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_alarm_runtime_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Emergency alarm runtime UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Domain UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "service_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Service name";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "service_state";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Service state";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "device_state";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Device state";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "device_endpoint";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Device endpoint";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_heartbeat";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last heartbeat";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_device_response";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last device response";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_error";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last error";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update date";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Update user";

?>
